### ISSUE TITLE
The `--num=all` paramater doesn't work anymore

### ISSUE THREAD

**Issue by gabrielesvelto** [willkg/crashstats-tools#26]
I just noticed it after upgrading from 1.0.4 to 1.1.0. This used to work:
```
supersearch --num=all --modules_in_stack libfreetype.so.6/FDA454F63593C15FA576037289D3F1F20
```
But now it fails with this error:
```
Error: Invalid value for '--num': all is not a valid integer
```

**Comment by willkg** [comment]
Oh poop. I messed that up. I'll fix that.

**Comment by willkg** [comment]
I pushed out v1.1.1 which has this fix. Sorry about that!
